// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace MigrationRunnerExtension
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidMigrationRunnerExtensionPackageString = "e57d496e-315d-4cad-83c9-b1b43543270b";
        public static Guid guidMigrationRunnerExtensionPackage = new Guid(guidMigrationRunnerExtensionPackageString);

        public const string guidMigrationRunnerExtensionPackageCmdSetString = "5c238ea4-0b83-4730-8948-1014f08c7c48";
        public static Guid guidMigrationRunnerExtensionPackageCmdSet = new Guid(guidMigrationRunnerExtensionPackageCmdSetString);

        public const string guidImagesString = "82eead59-01d6-4554-82af-f4227ebdbdcc";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MigrationRunnerToolWindowCommandId = 0x0100;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}